apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "longhorn-restorer.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "longhorn-restorer.name" . }}
    chart: {{ include "longhorn-restorer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "longhorn-restorer.fullname" . }}:jobs-volumes-manager
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - "longhorn.io"
  - "batch"
  resources:
  - "volumes"
  - "jobs"
  - "cronjobs"
  verbs:
  - "get"
  - "watch"
  - "create"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "longhorn-restorer.fullname" . }}:jobs-volumes-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "longhorn-restorer.fullname" . }}:jobs-volumes-manager
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "longhorn-restorer.fullname" . }}
  namespace: {{ .Release.Namespace }}